// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { PrismaClient } from "@prisma/client";

export const prisma = new PrismaClient({
  adapter: process.env.DATABASE_URL, // <-- This is your Supabase URL
});

