'use client';

import { useState, useCallback, useEffect } from 'react';
import { 
  ReactFlow, 
  Controls, 
  Background, 
  useNodesState, 
  useEdgesState, 
  addEdge,
  Connection,
  Edge,
  Node,
  Panel,
  NodeTypes
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import { UserStoryNode } from './nodes/UserStoryNode';
import { ScreenNode } from './nodes/ScreenNode';
import { Plus, Sparkles, Save, Share2 } from 'lucide-react';

const nodeTypes: NodeTypes = {
  userStory: UserStoryNode,
  screen: ScreenNode,
};

const initialNodes: Node[] = [];
const initialEdges: Edge[] = [];

interface VisualCanvasProps {
  projectId: string;
}

export function VisualCanvas({ projectId }: VisualCanvasProps) {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);
  const [isSaving, setIsSaving] = useState(false);

  // Load canvas data
  useEffect(() => {
    const loadCanvas = async () => {
      try {
        const res = await fetch(`/api/projects/${projectId}/canvas`);
        if (res.ok) {
          const data = await res.json();
          if (data.content && data.content.nodes) {
            setNodes(data.content.nodes);
            setEdges(data.content.edges || []);
          }
        }
      } catch (error) {
        console.error('Failed to load canvas:', error);
      }
    };
    loadCanvas();
  }, [projectId, setNodes, setEdges]);

  // Save canvas data
  const handleSave = async () => {
    setIsSaving(true);
    try {
      await fetch(`/api/projects/${projectId}/canvas`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ nodes, edges }),
      });
    } catch (error) {
      console.error('Failed to save canvas:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const onConnect = useCallback(
    (params: Connection) => setEdges((eds) => addEdge({ ...params, animated: true, style: { stroke: '#2EE6D6' } }, eds)),
    [setEdges],
  );

  const onAddNode = (type: string) => {
    const id = Math.random().toString(36).substr(2, 9);
    const newNode: Node = {
        id,
        type,
        position: { x: Math.random() * 400, y: Math.random() * 400 },
        data: { label: `New ${type}`, description: 'Edit this description...' }
    };
    setNodes((nds) => [...nds, newNode]);
  };

  const onAIGenerate = () => {
    // Stub for AI generation
    const id = Math.random().toString(36).substr(2, 9);
    const aiNode: Node = {
        id,
        type: 'userStory',
        position: { x: 600, y: 400 },
        data: { label: 'AI Generated Story', description: 'Automatically generated by BlueprintAI based on context.' }
    };
    setNodes((nds) => [...nds, aiNode]);
  };

  return (
    <div className="w-full h-full bg-cloud relative">
      <div className="absolute top-4 right-4 z-10 flex gap-2">
         <button 
           onClick={handleSave} 
           disabled={isSaving}
           className="bg-white p-2 rounded-md shadow-sm border border-border hover:bg-gray-50 text-navy disabled:opacity-50"
           title="Save Canvas"
         >
           <Save className={`w-5 h-5 ${isSaving ? 'animate-pulse' : ''}`} />
         </button>
      </div>

      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        nodeTypes={nodeTypes}
        fitView
        className="bg-cloud"
      >
        <Background color="#cbd5e1" gap={16} size={1} />
        <Controls className="bg-white border-border shadow-sm" />
        
        {/* Top Toolbar Panel */}
        <Panel position="top-center" className="bg-white p-2 rounded-full shadow-lg border border-border flex gap-2 mt-4">
            <button onClick={() => onAddNode('userStory')} className="p-2 hover:bg-gray-100 rounded-full text-navy" title="Add User Story">
                <Plus className="w-5 h-5" />
            </button>
            <div className="w-px bg-gray-200 mx-1"></div>
            <button onClick={onAIGenerate} className="flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-navy to-blue-900 text-white rounded-full hover:shadow-md transition-all">
                <Sparkles className="w-4 h-4 text-cyan" />
                <span className="text-xs font-bold">Generate Flow</span>
            </button>
        </Panel>

      </ReactFlow>
    </div>
  );
}
