'use client';

import { useState, useCallback } from 'react';
import { 
  ReactFlow, 
  Controls, 
  Background, 
  useNodesState, 
  useEdgesState, 
  addEdge,
  Connection,
  Edge,
  Node,
  Panel
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import { UserStoryNode } from './nodes/UserStoryNode';
import { ScreenNode } from './nodes/ScreenNode';
import { Plus, Sparkles, Save, Share2 } from 'lucide-react';

const nodeTypes = {
  userStory: UserStoryNode,
  screen: ScreenNode,
};

const initialNodes: Node[] = [
  { 
    id: '1', 
    type: 'userStory', 
    position: { x: 100, y: 100 }, 
    data: { label: 'Login', description: 'As a user, I want to login with email/password' } 
  },
  { 
    id: '2', 
    type: 'screen', 
    position: { x: 500, y: 50 }, 
    data: { label: 'Login Screen' } 
  },
];

const initialEdges: Edge[] = [
  { id: 'e1-2', source: '1', target: '2', animated: true, style: { stroke: '#2EE6D6', strokeWidth: 2 } },
];

export function VisualCanvas() {
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  const onConnect = useCallback(
    (params: Connection) => setEdges((eds) => addEdge({ ...params, animated: true, style: { stroke: '#2EE6D6' } }, eds)),
    [setEdges],
  );

  const onAddNode = (type: string) => {
    const id = Math.random().toString(36).substr(2, 9);
    const newNode: Node = {
        id,
        type,
        position: { x: Math.random() * 400, y: Math.random() * 400 },
        data: { label: `New ${type}`, description: 'Edit this description...' }
    };
    setNodes((nds) => [...nds, newNode]);
  };

  const onAIGenerate = () => {
    // Stub for AI generation
    const id = Math.random().toString(36).substr(2, 9);
    const aiNode: Node = {
        id,
        type: 'userStory',
        position: { x: 600, y: 400 },
        data: { label: 'AI Generated Story', description: 'Automatically generated by BlueprintAI based on context.' }
    };
    setNodes((nds) => [...nds, aiNode]);
  };

  return (
    <div className="w-full h-full bg-cloud">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        nodeTypes={nodeTypes}
        fitView
        className="bg-cloud"
      >
        <Background color="#cbd5e1" gap={16} size={1} />
        <Controls className="bg-white border-border shadow-sm" />
        
        {/* Top Toolbar Panel */}
        <Panel position="top-center" className="bg-white p-2 rounded-full shadow-lg border border-border flex gap-2 mt-4">
            <button onClick={() => onAddNode('userStory')} className="p-2 hover:bg-gray-100 rounded-full text-navy" title="Add User Story">
                <Plus className="w-5 h-5" />
            </button>
            <div className="w-px bg-gray-200 mx-1"></div>
            <button onClick={onAIGenerate} className="flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-navy to-blue-900 text-white rounded-full hover:shadow-md transition-all">
                <Sparkles className="w-4 h-4 text-cyan" />
                <span className="text-xs font-bold">Generate Flow</span>
            </button>
        </Panel>

      </ReactFlow>
    </div>
  );
}
